In [1]:
#Importing the dependencies
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Storing the csvpaths
csvpath_confirmed="time_series_19-covid-Confirmed.csv"
csvpath_deaths="time_series_19-covid-Deaths.csv"
csvpath_recovered="time_series_19-covid-Recovered.csv"

In [3]:
#Reading into a pandas DataFrame
Confirmed_df1=pd.read_csv(csvpath_confirmed)
Deaths_df1=pd.read_csv(csvpath_deaths)
Recovered_df1=pd.read_csv(csvpath_recovered)

In [4]:
#Manipulating the Confirmed dataframe
#Dropping the colums which are not required
Confirmed_df1.drop(columns=["Province/State","Lat","Long"],inplace=True)

In [5]:
#Filling NaN with a 0 for calculations
Confirmed_df1=Confirmed_df1.fillna(0)
Confirmed_df1.head(20)
#len(Confirmed_df1)

,Country/Region,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,...,3/4/20,3/5/20,3/6/20,3/7/20,3/8/20,3/9/20,3/10/20,3/11/20,3/12/20,3/13/20
0,Thailand,2,3,5,7,8,8,14,14,14,...,43,47,48,50,50,50,53,59,70,75
1,Japan,2,1,2,2,4,4,7,7,11,...,331,360,420,461,502,511,581,639,639,701
2,Singapore,0,1,3,3,4,5,7,7,10,...,110,117,130,138,150,150,160,178,178,200
3,Nepal,0,0,0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,Malaysia,0,0,0,3,4,4,4,7,8,...,50,50,83,93,99,117,129,149,149,197
5,Canada,0,0,0,0,0,0,1,1,1,...,12,13,21,21,27,32,32,39,46,64
6,Australia,0,0,0,0,3,4,4,4,4,...,22,22,26,28,38,48,55,65,65,92
7,Australia,0,0,0,0,1,1,1,1,2,...,10,10,10,11,11,15,18,21,21,36
8,Australia,0,0,0,0,0,0,0,1,3,...,11,13,13,13,15,15,18,20,20,35
9,Cambodia,0,0,0,0,0,1,1,1,1,...,1,1,1,1,2,2,2,3,3,5
10,Sri Lanka,0,0,0,0,0,1,1,1,1,...,1,1,1,1,1,1,1,2,2,6
11,Germany,0,0,0,0,0,1,4,4,4,...,262,482,670,799,1040,1176,1457,1908,2078,3675
12,Finland,0,0,0,0,0,0,0,1,1,...,6,12,15,15,23,30,40,59,59,155
13,United Arab Emirates,0,0,0,0,0,0,0,4,4,...,27,29,29,45,45,45,74,74,85,85
14,Philippines,0,0,0,0,0,0,0,0,1,...,3,3,5,6,10,20,33,49,52,64
15,India,0,0,0,0,0,0,0,0,1,...,28,30,31,34,39,43,56,62,73,82
16,Italy,0,0,0,0,0,0,0,0,0,...,3089,3858,4636,5883,7375,9172,10149,12462,12462,17660
17,Sweden,0,0,0,0,0,0,0,0,0,...,35,94,101,161,203,248,355,500,599,814
18,Spain,0,0,0,0,0,0,0,0,0,...,222,259,400,500,673,1073,1695,2277,2277,5232
19,Australia,0,0,0,0,0,0,0,0,0,...,5,5,7,7,7,7,7,9,9,16

In [6]:
#Grouping the Confirmed cases dataframe by Country/Region
Confirmed_group=Confirmed_df1.groupby(["Country/Region"])


#Creating the final Confirmed dataframe to be used further
Confirmed_final=Confirmed_group.sum()
Confirmed_final.head(20)
#len(Confirmed_final)

,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,3/4/20,3/5/20,3/6/20,3/7/20,3/8/20,3/9/20,3/10/20,3/11/20,3/12/20,3/13/20
Country/Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,4,4,5,7,7,7
Albania,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,10,12,23,33
Algeria,0,0,0,0,0,0,0,0,0,0,...,12,12,17,17,19,20,20,20,24,26
Andorra,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Antigua and Barbuda,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Argentina,0,0,0,0,0,0,0,0,0,0,...,1,1,2,8,12,12,17,19,19,31
Armenia,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,4,8
Aruba,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
Australia,0,0,0,0,4,5,5,6,9,9,...,52,55,60,63,76,91,107,128,128,200
Austria,0,0,0,0,0,0,0,0,0,0,...,29,41,55,79,104,131,182,246,302,504
Azerbaijan,0,0,0,0,0,0,0,0,0,0,...,3,6,6,9,9,9,11,11,11,15
Bahrain,0,0,0,0,0,0,0,0,0,0,...,52,55,60,85,85,95,110,195,195,189
Bangladesh,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3,3,3,3,3,3
Belarus,0,0,0,0,0,0,0,0,0,0,...,6,6,6,6,6,6,9,9,12,27
Belgium,0,0,0,0,0,0,0,0,0,0,...,23,50,109,169,200,239,267,314,314,559
Bhutan,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,1,1,1,1,1
Bolivia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,2,3
Bosnia and Herzegovina,0,0,0,0,0,0,0,0,0,0,...,0,2,2,3,3,3,5,7,11,13
Brazil,0,0,0,0,0,0,0,0,0,0,...,4,4,13,13,20,25,31,38,52,151
Brunei,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,11,11,37

In [7]:
#Manipulating the Deaths dataframe
#Dropping the colums which are not required
Deaths_df1.drop(columns=["Province/State","Lat","Long"],inplace=True)

In [8]:
#Filling NaN with a 0 for calculations
Deaths_df1=Deaths_df1.fillna(0)
Deaths_df1.head(20)
#len(Confirmed_df1)

,Country/Region,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,...,3/4/20,3/5/20,3/6/20,3/7/20,3/8/20,3/9/20,3/10/20,3/11/20,3/12/20,3/13/20
0,Thailand,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
1,Japan,0,0,0,0,0,0,0,0,0,...,6,6,6,6,6,10,10,15,16,19
2,Singapore,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Nepal,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Malaysia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Canada,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,1,1
6,Australia,0,0,0,0,0,0,0,0,0,...,1,1,1,1,2,2,2,2,2,2
7,Australia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,Australia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,Cambodia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,Sri Lanka,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,Germany,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,2,3,3,7
12,Finland,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,United Arab Emirates,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,Philippines,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,2,5
15,India,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,2
16,Italy,0,0,0,0,0,0,0,0,0,...,107,148,197,233,366,463,631,827,827,1266
17,Sweden,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
18,Spain,0,0,0,0,0,0,0,0,0,...,2,3,5,10,17,28,35,54,55,133
19,Australia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
#Grouping the Death cases dataframe by Country/Region
Deaths_group=Deaths_df1.groupby(["Country/Region"])


#Creating the final Death dataframe to be used further
Deaths_final=Deaths_group.sum()
Deaths_final.head(20)
#len(Deaths_final)

,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,3/4/20,3/5/20,3/6/20,3/7/20,3/8/20,3/9/20,3/10/20,3/11/20,3/12/20,3/13/20
Country/Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Albania,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
Algeria,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,2
Andorra,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Antigua and Barbuda,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Argentina,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,1,1,1,2
Armenia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Aruba,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Australia,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,3,3,3,3,3,3
Austria,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
Azerbaijan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Bahrain,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Bangladesh,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Belarus,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Belgium,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3,3,3
Bhutan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Bolivia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Bosnia and Herzegovina,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Brazil,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Brunei,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
#Manipulating the Recovered dataframe
#Dropping the colums which are not required
Recovered_df1.drop(columns=["Province/State","Lat","Long"],inplace=True)

In [11]:
#Filling NaN with a 0 for calculations
Recovered_df1=Recovered_df1.fillna(0)
Recovered_df1.head(20)
#len(Recovered_df1)

,Country/Region,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,...,3/4/20,3/5/20,3/6/20,3/7/20,3/8/20,3/9/20,3/10/20,3/11/20,3/12/20,3/13/20
0,Thailand,0,0,0,0,2,2,5,5,5,...,31,31,31,31,31,31,33,34,34,35
1,Japan,0,0,0,0,1,1,1,1,1,...,43,43,46,76,76,76,101,118,118,118
2,Singapore,0,0,0,0,0,0,0,0,0,...,78,78,78,78,78,78,78,96,96,97
3,Nepal,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
4,Malaysia,0,0,0,0,0,0,0,0,0,...,22,22,22,23,24,24,24,26,26,26
5,Canada,0,0,0,0,0,0,0,0,0,...,3,3,3,4,4,4,4,4,4,4
6,Australia,0,0,0,0,0,0,0,0,2,...,4,4,4,4,4,4,4,4,4,4
7,Australia,0,0,0,0,0,0,0,0,0,...,4,7,7,7,7,7,7,7,7,8
8,Australia,0,0,0,0,0,0,0,0,0,...,1,8,8,8,8,8,8,8,8,8
9,Cambodia,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
10,Sri Lanka,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
11,Germany,0,0,0,0,0,0,0,0,0,...,16,16,17,18,18,18,18,25,25,46
12,Finland,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
13,United Arab Emirates,0,0,0,0,0,0,0,0,0,...,5,5,5,7,7,7,12,17,17,17
14,Philippines,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,2,2,2,2
15,India,0,0,0,0,0,0,0,0,0,...,3,3,3,3,3,3,4,4,4,4
16,Italy,0,0,0,0,0,0,0,0,0,...,276,414,523,589,622,724,724,1045,1045,1439
17,Sweden,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,1,1
18,Spain,0,0,0,0,0,0,0,0,0,...,2,2,2,30,30,32,32,183,183,193
19,Australia,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,3

In [12]:
#Grouping the Recovered cases dataframe by Country/Region
Recovered_group=Recovered_df1.groupby(["Country/Region"])


#Creating the final Recovered dataframe to be used further
Recovered_final=Recovered_group.sum()
Recovered_final.head(20)
#len(Recovered_final)

,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,3/4/20,3/5/20,3/6/20,3/7/20,3/8/20,3/9/20,3/10/20,3/11/20,3/12/20,3/13/20
Country/Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Albania,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Algeria,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,8,8
Andorra,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Antigua and Barbuda,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Argentina,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Armenia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Aruba,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Australia,0,0,0,0,0,0,0,0,2,2,...,11,21,21,21,21,21,21,21,21,23
Austria,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,4,4,4,6
Azerbaijan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3,3,3
Bahrain,0,0,0,0,0,0,0,0,0,0,...,0,0,4,4,4,14,22,35,35,44
Bangladesh,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Belarus,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,3,3,3,3
Belgium,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Bhutan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Bolivia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Bosnia and Herzegovina,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Brazil,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Brunei,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
Confirmed_final.dtypes

1/22/20    int64
1/23/20    int64
1/24/20    int64
1/25/20    int64
1/26/20    int64
1/27/20    int64
1/28/20    int64
1/29/20    int64
1/30/20    int64
1/31/20    int64
2/1/20     int64
2/2/20     int64
2/3/20     int64
2/4/20     int64
2/5/20     int64
2/6/20     int64
2/7/20     int64
2/8/20     int64
2/9/20     int64
2/10/20    int64
2/11/20    int64
2/12/20    int64
2/13/20    int64
2/14/20    int64
2/15/20    int64
2/16/20    int64
2/17/20    int64
2/18/20    int64
2/19/20    int64
2/20/20    int64
2/21/20    int64
2/22/20    int64
2/23/20    int64
2/24/20    int64
2/25/20    int64
2/26/20    int64
2/27/20    int64
2/28/20    int64
2/29/20    int64
3/1/20     int64
3/2/20     int64
3/3/20     int64
3/4/20     int64
3/5/20     int64
3/6/20     int64
3/7/20     int64
3/8/20     int64
3/9/20     int64
3/10/20    int64
3/11/20    int64
3/12/20    int64
3/13/20    int64
dtype: object

In [17]:
#Creating a dataframe for Singapore
Singapore_df=pd.DataFrame({"Dates":Confirmed_final.loc["Singapore",:].index.tolist(),\
                           "#Cummulative Confirmed Cases":Confirmed_final.loc["Singapore",:].tolist(),\
                           "#Cummulative Death Cases":Deaths_final.loc["Singapore",:].tolist(),
                           "#Cummulative Recovered Cases":Recovered_final.loc["Singapore",:].tolist()})

In [22]:
Singapore_df

,Dates,#Cummulative Confirmed Cases,#Cummulative Death Cases,#Cummulative Recovered Cases
0,1/22/20,0,0,0
1,1/23/20,1,0,0
2,1/24/20,3,0,0
3,1/25/20,3,0,0
4,1/26/20,4,0,0
5,1/27/20,5,0,0
6,1/28/20,7,0,0
7,1/29/20,7,0,0
8,1/30/20,10,0,0
9,1/31/20,13,0,0
10,2/1/20,16,0,0
11,2/2/20,18,0,0
12,2/3/20,18,0,0
13,2/4/20,24,0,0
14,2/5/20,28,0,0
15,2/6/20,28,0,0
16,2/7/20,30,0,0
17,2/8/20,33,0,2
18,2/9/20,40,0,2
19,2/10/20,45,0,2
20,2/11/20,47,0,9
21,2/12/20,50,0,15
22,2/13/20,58,0,15
23,2/14/20,67,0,17
24,2/15/20,72,0,18
25,2/16/20,75,0,18
26,2/17/20,77,0,24
27,2/18/20,81,0,29
28,2/19/20,84,0,34
29,2/20/20,84,0,34
30,2/21/20,85,0,37
31,2/22/20,85,0,37
32,2/23/20,89,0,51
33,2/24/20,89,0,51
34,2/25/20,91,0,53
35,2/26/20,93,0,62
36,2/27/20,93,0,62
37,2/28/20,93,0,62
38,2/29/20,102,0,72
39,3/1/20,106,0,72
40,3/2/20,108,0,78
41,3/3/20,110,0,78
42,3/4/20,110,0,78
43,3/5/20,117,0,78
44,3/6/20,130,0,78
45,3/7/20,138,0,78
46,3/8/20,150,0,78
47,3/9/20,150,0,78
48,3/10/20,160,0,78
49,3/11/20,178,0,96
50,3/12/20,178,0,96
51,3/13/20,200,0,97

In [20]:
confirmed_total_singapore=Singapore_df.loc[len(Singapore_df)-1,"#Cummulative Confirmed Cases"]
confirmed_total_singapore

200

In [24]:
death_total_singapore=Singapore_df.loc[len(Singapore_df)-1,"#Cummulative Death Cases"]
death_total_singapore

0

In [25]:
recovered_total_singapore=Singapore_df.loc[len(Singapore_df)-1,"#Cummulative Recovered Cases"]
recovered_total_singapore

97